version: '3.7'

services:
  itsme:
    container_name: itsme
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/itsme'
      - '/usr/src/itsme/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
